export const ADD_CHARACTER = 'ADD_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const DESELECT_CHARACTER = 'DESELECT_CHARACTER';